CREATE TYPE FRAISEUSE_TREATMENT_TYPES AS ENUM ('COLLIMATEUR', 'COMPENSATEUR', 'MODULATEUR');

CREATE TABLE TreatmentFraiseuseProgram
(
   fraiseuse_program_id SERIAL PRIMARY KEY,
   dossier INTEGER NOT NULL,
   program_type FRAISEUSE_TREATMENT_TYPES NOT NULL,
   timestamp TIMESTAMP NOT NULL,
   program TEXT
);

CREATE TYPE FRAISEUSE_MISC_TYPES AS ENUM ('HF', 'ELEC', 'PROTON', 'AIMA', 'S2C2', 'MEDICYC', 'SITEEST', 'DIVERS', 'REFPROTON');


CREATE TABLE MiscFraiseuseProgram
(
   fraiseuse_program_id SERIAL PRIMARY KEY,
   id VARCHAR(50) NOT NULL,
   program_type FRAISEUSE_MISC_TYPES NOT NULL,
   timestamp TIMESTAMP NOT NULL,
   program TEXT
);
